name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image front
      run: docker build -t front-end-service:latest .
      
    - name: Push Docker Image front
      run: docker push front-end-service:latest

    - name: Build Docker Image order
      run: docker build -t order-service:latest .
      
    - name: Push Docker Image order
      run: docker push order-service:latest

    - name: Build Docker Image user
      run: docker build -t user-service:latest .
      
    - name: Push Docker Image user
      run: docker push user-service:latest
