name: Docker image build and push

on:
  push:
    branches:
      - "main"

jobs:
  push_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: taobrmd/front-end-react
          - context: order-service
            image: taobrmd/order-service
          - context: user-service
            image: taobrmd/user-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ../../cicd-project-main/${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}:${{ github.sha }}