name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t taobrmd/frontend:latest $GITHUB_WORKSPACE/cicd-project-main/front-end-react/
        docker push taobrmd/frontend:latest

    - name: Build and Push Order Service Docker Image
      run: |
        docker build -t taobrmd/order-service:latest $GITHUB_WORKSPACE/cicd-project-main/order-service/
        docker push taobrmd/order-service:latest

    - name: Build and Push User Service Docker Image
      run: |
        docker build -t taobrmd/user-service:latest $GITHUB_WORKSPACE/cicd-project-main/user-service/
        docker push taobrmd/user-service:latest
