name: 4 Versionning

on:
  push:
    branches:
      - .*[1-9][0-9]*\.[0-9]+\.[0-9]+
  create:
    branches:
      - .*[1-9][0-9]*\.[0-9]+\.[0-9]+


jobs:
  versionning:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Version Number
      id: extract_version
      run: echo "::set-output name=VERSION_NUMBER::$(echo ${{ github.ref }} | grep -oE '[1-9][0-9]*\.[0-9]+\.[0-9]+')"
      if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'branch')

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t taobrmd/frontend:${{ steps.extract_version.outputs.VERSION_NUMBER }} $GITHUB_WORKSPACE/cicd-project-main/front-end-react/
        docker push taobrmd/frontend:${{ steps.extract_version.outputs.VERSION_NUMBER }}

    - name: Build and Push Order Service Docker Image
      run: |
        docker build -t taobrmd/order-service:${{ steps.extract_version.outputs.VERSION_NUMBER }} $GITHUB_WORKSPACE/cicd-project-main/order-service/
        docker push taobrmd/order-service:${{ steps.extract_version.outputs.VERSION_NUMBER }}

    - name: Build and Push User Service Docker Image
      run: |
        docker build -t taobrmd/user-service:${{ steps.extract_version.outputs.VERSION_NUMBER }} $GITHUB_WORKSPACE/cicd-project-main/user-service/
        docker push taobrmd/user-service:${{ steps.extract_version.outputs.VERSION_NUMBER }}