name: Docker image build and push version

on:
  push:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: front-end-react
            image_name: taobrmd/front-end-react
          - context: order-service
            image_name: taobrmd/order-service
          - context: user-service
            image_name: taobrmd/user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Build and push ${{ matrix.context }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ matrix.image_name }}:${{ steps.extract_branch.outputs.branch }}